services:
  - type: web
    name: to-do-list-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run_migrations.py && gunicorn application:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: to-do-list-db
          property: connectionString