"""Add user_tasks table for collaboration

Revision ID: c82f60104435
Revises: c028d5f92b05
Create Date: 2025-09-27 07:35:05.371436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82f60104435'
down_revision = 'c028d5f92b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_index('ix_admins_email')
        batch_op.drop_index('ix_admins_username')
        batch_op.create_unique_constraint(batch_op.f('uq_admins_email'), ['email'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_admins_email'), type_='unique')
        batch_op.create_index('ix_admins_username', ['username'], unique=1)
        batch_op.create_index('ix_admins_email', ['email'], unique=1)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
